version: "3"

services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - backnet
#    volumes:
#      - "./telegram_bot/db_data/:/data/db"

  backend:
    container_name: signum_bot_backend
    build: ./telegram_bot/backend
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "8080:80"
    networks:
      - backnet
      - frontnet

  frontend-service:
    container_name: signum_bot
    build: ./telegram_bot/frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontnet

networks:
  frontnet:
  backnet: