name: CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  testing:
    name: 'Check for source changes'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Get repository code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            telegram_bot
            tests_telegram_bot
            pyproject.toml
            pytest.ini
          sparse-checkout-cone-mode: false

      - name: Install dependencies
        run: poetry install --with test

      - name: Run tests
        run: poetry run pytest
