name: Backend CI
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - dev
      - backend
      - backend/*
      - backend-features
      - backend-features/*
  pull_request:
    branches:
      - dev
      - backend
      - backend/*
      - backend-features
      - backend-features/*
jobs:
  lint:
    uses: ./.github/workflows/telegram-bot-linting.yml

  testing:
    name: Testing backend
    needs: [ lint ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Get backend code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            telegram_bot/backend/*
          sparse-checkout-cone-mode: false

      - name: View folder contain
        run: |
          ls telegram_bot/backend -la

      - name: Install dependencies
        run: |
          cd telegram_bot/backend 
          poetry install --no-interaction --no-root --no-directory --with test

      - name: Run tests
        run: |
          cd telegram_bot/backend 
          poetry run pytest
